<Project Sdk="Microsoft.NET.Sdk">
  <Import Condition="Exists('../default.props')" Project="../default.props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>$(SolutionDir)out\$(Configuration)-$(PlatformSuffix)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>$(SolutionDir)out\$(Configuration)-$(PlatformSuffix)\</OutputPath>
  </PropertyGroup>

</Project>
